FROM alpine:3.15
ENV PYTHONUNBUFFERED 1
ENV HOST 0.0.0.0
ENV PORT 5000
ENV DEBUG 0
ENV DB_SQLITE 1
ENV DB_POSTGRESQL 0
ENV DB_HOST localhost
ENV DB_USER root
ENV DB_PASSWD passwd
ENV DB_PORT 5432
ENV DB_DB api

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apk update && \
    apk add --no-cache --virtual .build-deps gcc musl-dev \
    python3-dev libpq-dev postgresql-dev && \
    apk add --no-cache g++ py3-pip py3-numpy py3-pandas libpq

RUN cd /opt && mkdir config/
ADD /install.txt /opt/config/
RUN pip install --no-cache-dir -r /opt/config/install.txt
RUN apk del .build-deps

RUN mkdir /opt/api && mkdir /opt/api/dir_tabla
COPY api.py /opt/api/api.py
COPY models.py /opt/api/models.py
COPY views.py /opt/api/views.py
COPY run.py /opt/api/run.py

COPY start.sh /start.sh
RUN chmod +x /start.sh
ENTRYPOINT /start.sh
WORKDIR /opt
